env:
  global:
    - CC_TEST_REPORTER_ID=6f5cc561eebca1fafb832a0cd84dc0bbdc409940885236a43cdb21b1e189766e
sudo: false
language: ruby
rvm:
  - 2.4.2
before_install: gem install bundler -v 1.15.4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
